### ISSUE TITLE
Some errors running live tests

### ISSUE THREAD

**Issue by martinda** [cdancy/bitbucket-rest#146] opened 2018-08-08 03:24 UTC
I am not sure why, but I get failures running the live tests (master branch).

My question is: are live tests in a state where they are known to pass? If so, with which version of Bitbucket?

### Expected Behavior

Live tests should pass.

### Current Behavior

139 tests completed, 9 failed, 67 skipped

> Task :integTest FAILED

### Context

I am getting ready to add a couple new features (logging, create fork) but first I want to run the live tests.

### Steps to Reproduce (for bugs)

Running on a linux localhost:

```
./gradlew integTest \
    -Ptest.bitbucket.endpoint=http://localhost:7990 \
    -PtestBitbucketRestCredentials=admin:passwd
```

The executive summary of the problem I see is that Bitbucket sometimes returns HTTP 204 meaning no-content, but bitbucket-rest appears to expect content, and throws an exception.

An example of this HTTP 204 error is:
```
23:08:41.774 [Test worker] DEBUG org.jclouds.rest.internal.InvokeHttpMethod - >> invoking project:get
23:08:41.775 [Test worker] DEBUG org.jclouds.http.internal.JavaUrlHttpCommandExecutorService - Sending request -2035848655: GET http://127.0.0.1:7990/rest/api/1.0/projects/DEV HTTP/1.1
23:08:41.775 [Test worker] DEBUG jclouds.headers - >> GET http://127.0.0.1:7990/rest/api/1.0/projects/DEV HTTP/1.1
23:08:41.775 [Test worker] DEBUG jclouds.headers - >> Accept: application/json
23:08:41.775 [Test worker] DEBUG jclouds.headers - >> Authorization: Basic bWFydGluOm1hcnRpbg==
23:08:41.805 [Test worker] DEBUG org.jclouds.http.internal.JavaUrlHttpCommandExecutorService - Receiving response -2035848655: HTTP/1.1 200 null
23:08:41.805 [Test worker] DEBUG jclouds.headers - << HTTP/1.1 200 null
23:08:41.805 [Test worker] DEBUG jclouds.headers - << Transfer-Encoding: chunked
23:08:41.805 [Test worker] DEBUG jclouds.headers - << X-AREQUESTID: @12IZ2M8x1388x708x0
23:08:41.805 [Test worker] DEBUG jclouds.headers - << X-ASEN: SEN-11797004
23:08:41.805 [Test worker] DEBUG jclouds.headers - << X-Content-Type-Options: nosniff
23:08:41.805 [Test worker] DEBUG jclouds.headers - << X-AUSERNAME: martin
23:08:41.805 [Test worker] DEBUG jclouds.headers - << Vary: X-AUSERNAME,Accept-Encoding
23:08:41.805 [Test worker] DEBUG jclouds.headers - << X-AUSERID: 1
23:08:41.805 [Test worker] DEBUG jclouds.headers - << Date: Wed, 08 Aug 2018 03:08:40 GMT
23:08:41.805 [Test worker] DEBUG jclouds.headers - << Cache-Control: no-cache, no-transform
23:08:41.805 [Test worker] DEBUG jclouds.headers - << Content-Type: application/json;charset=UTF-8
23:08:41.805 [Test worker] DEBUG jclouds.wire - << "{"key":"DEV","id":43,"name":"DEV","public":false,"type":"NORMAL","links":{"self":[{"href":"http://127.0.0.1:7990/projects/DEV"}]}}"
23:08:41.811 [Test worker] DEBUG org.jclouds.rest.internal.InvokeHttpMethod - >> invoking RepositoryApi.create
23:08:41.811 [Test worker] DEBUG org.jclouds.http.internal.JavaUrlHttpCommandExecutorService - Sending request 1317183856: POST http://127.0.0.1:7990/rest/api/1.0/projects/DEV/repos HTTP/1.1
23:08:41.811 [Test worker] DEBUG jclouds.wire - >> "{"name":"TUDDIXQGGB","scmId":"git","forkable":true}"
23:08:41.811 [Test worker] DEBUG jclouds.headers - >> POST http://127.0.0.1:7990/rest/api/1.0/projects/DEV/repos HTTP/1.1
23:08:41.811 [Test worker] DEBUG jclouds.headers - >> Accept: application/json
23:08:41.811 [Test worker] DEBUG jclouds.headers - >> Authorization: Basic bWFydGluOm1hcnRpbg==
23:08:41.811 [Test worker] DEBUG jclouds.headers - >> Content-Type: application/json
23:08:41.811 [Test worker] DEBUG jclouds.headers - >> Content-Length: 51
23:08:41.845 [Test worker] DEBUG org.jclouds.http.internal.JavaUrlHttpCommandExecutorService - Receiving response 1317183856: HTTP/1.1 201 null
23:08:41.845 [Test worker] DEBUG jclouds.headers - << HTTP/1.1 201 null
23:08:41.845 [Test worker] DEBUG jclouds.headers - << Transfer-Encoding: chunked
23:08:41.845 [Test worker] DEBUG jclouds.headers - << X-AREQUESTID: @12IZ2M8x1388x709x0
23:08:41.845 [Test worker] DEBUG jclouds.headers - << X-ASEN: SEN-11797004
23:08:41.845 [Test worker] DEBUG jclouds.headers - << X-Content-Type-Options: nosniff
23:08:41.845 [Test worker] DEBUG jclouds.headers - << X-AUSERNAME: martin
23:08:41.845 [Test worker] DEBUG jclouds.headers - << Vary: X-AUSERNAME,Accept-Encoding
23:08:41.845 [Test worker] DEBUG jclouds.headers - << X-AUSERID: 1
23:08:41.845 [Test worker] DEBUG jclouds.headers - << Date: Wed, 08 Aug 2018 03:08:40 GMT
23:08:41.845 [Test worker] DEBUG jclouds.headers - << Location: http://127.0.0.1:7990/rest/api/1.0/projects/DEV/repos/tuddixqggb
23:08:41.845 [Test worker] DEBUG jclouds.headers - << Cache-Control: no-cache, no-transform
23:08:41.845 [Test worker] DEBUG jclouds.headers - << Content-Type: application/json;charset=UTF-8
23:08:41.845 [Test worker] DEBUG jclouds.wire - << "{"slug":"tuddixqggb","id":43,"name":"TUDDIXQGGB","scmId":"git","state":"AVAILABLE","statusMessage":"Available","forkable":true,"project":{"key":"DEV","id":43,"name":"DEV","public":false,"type":"NORMAL","links":{"self":[{"href":"http://127.0.0.1:7990/projects/DEV"}]}},"public":false,"links":{"clone":[{"href":"http://martin@127.0.0.1:7990/scm/dev/tuddixqggb.git","name":"http"},{"href":"ssh://git@127.0.0.1:7999/dev/tuddixqggb.git","name":"ssh"}],"self":[{"href":"http://127.0.0.1:7990/projects/DEV/repos/tuddixqggb/browse"}]}}"
git-init: Initialized empty Git repository in /home/martin/git/bitbucket-rest/build/integ-projects/a356505d0c0b422b9d52f8b9d9325d65/.git/
git-add-1: 
git-commit-1: [master (root-commit) ab596b4] added
 1 file changed, 1 insertion(+)
 create mode 100644 e8a25252a2874adbaeebc5c3e8af3ddf.txt
git-add-2: 
git-commit-2: [master 5b42087] added
 1 file changed, 1 insertion(+), 1 deletion(-)
git-tag-commit: 
git-add-1: 
git-commit-1: [master 7c4a7dc] added
 1 file changed, 1 insertion(+)
 create mode 100644 cd4d605f8e5c441faddd41a08772c6f2.txt
git-add-2: 
git-commit-2: [master 98d1eda] added
 1 file changed, 1 insertion(+), 1 deletion(-)
git-tag-commit: 
git-add-1: 
git-commit-1: [master 9cdea85] added
 1 file changed, 1 insertion(+)
 create mode 100644 e5e9102e28bb496f863f8cb501f6bc03.txt
git-add-2: 
git-commit-2: [master af30371] added
 1 file changed, 1 insertion(+), 1 deletion(-)
git-tag-commit: 
git-push: 
git-branch: 
git-branch-add: 
git-branch-commit: [4b056ed6af42433384d498ad32dd0522 cdaab11] added
 1 file changed, 1 insertion(+)
 create mode 100644 b0a44c6e0d2e493995828f3e8a00265c.txt
git-branch-push: 
23:08:41.945 [Test worker] DEBUG org.jclouds.rest.internal.InvokeHttpMethod - >> invoking branch:get-default
23:08:41.946 [Test worker] DEBUG org.jclouds.http.internal.JavaUrlHttpCommandExecutorService - Sending request -264870076: GET http://127.0.0.1:7990/rest/api/1.0/projects/DEV/repos/TUDDIXQGGB/branches/default HTTP/1.1
23:08:41.946 [Test worker] DEBUG jclouds.headers - >> GET http://127.0.0.1:7990/rest/api/1.0/projects/DEV/repos/TUDDIXQGGB/branches/default HTTP/1.1
23:08:41.946 [Test worker] DEBUG jclouds.headers - >> Accept: application/json
23:08:41.946 [Test worker] DEBUG jclouds.headers - >> Authorization: Basic bWFydGluOm1hcnRpbg==
23:08:41.956 [Test worker] DEBUG org.jclouds.http.internal.JavaUrlHttpCommandExecutorService - Receiving response -264870076: HTTP/1.1 204 null
23:08:41.956 [Test worker] DEBUG jclouds.headers - << HTTP/1.1 204 null
23:08:41.956 [Test worker] DEBUG jclouds.headers - << X-AREQUESTID: @12IZ2M8x1388x714x0
23:08:41.956 [Test worker] DEBUG jclouds.headers - << X-ASEN: SEN-11797004
23:08:41.957 [Test worker] DEBUG jclouds.headers - << X-Content-Type-Options: nosniff
23:08:41.957 [Test worker] DEBUG jclouds.headers - << X-AUSERNAME: martin
23:08:41.957 [Test worker] DEBUG jclouds.headers - << Vary: Cookie
23:08:41.957 [Test worker] DEBUG jclouds.headers - << Vary: X-AUSERID
23:08:41.957 [Test worker] DEBUG jclouds.headers - << Vary: X-AUSERNAME
23:08:41.957 [Test worker] DEBUG jclouds.headers - << X-AUSERID: 1
23:08:41.957 [Test worker] DEBUG jclouds.headers - << Date: Wed, 08 Aug 2018 03:08:40 GMT
23:08:41.957 [Test worker] ERROR org.jclouds.http.functions.ParseJson - Error parsing input: null
java.lang.NullPointerException: null
	at org.jclouds.http.functions.ParseJson.apply(ParseJson.java:60)
	at org.jclouds.http.functions.ParseJson.apply(ParseJson.java:41)
	at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:91)
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:74)
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:45)
	at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy66.getDefault(Unknown Source)
	at com.cdancy.bitbucket.rest.features.BranchApiLiveTest.init(BranchApiLiveTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:166)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:139)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:89)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
```

### Your Environment

Linux.
Bitbucket 5.8.1.
The master branch (ae736ee) of bitbucket-rest.

**Comment by cdancy** [comment] 2018-08-08 13:31
Live tests should more/less pass if you're running as an admin user. I generally just target the latest and greatest version of bitbucket. It's entirely possible you are hitting a bug that is only sometimes reproducible. Is this reproducible every time? Is this the only test that fails? Also seems strange that their is no default branch set but maybe that's OK?

**Comment by martinda** [comment] 2018-08-08 15:07
The user is an admin user. It is reproducible every time.

What happens when you run the live tests? Do they all pass? Which version of bitbucket do you use?

Here is another one I get:
```
09:53:03.825 [Test worker] DEBUG org.jclouds.rest.internal.InvokeHttpMethod - >> invoking RepositoryApi.updatePullRequestSettings
09:53:03.826 [Test worker] DEBUG org.jclouds.http.internal.JavaUrlHttpCommandExecutorService - Sending request 1402237253: POST http://127.0.0.1:7990/rest/api/1.0/projects/DEV/repos/YUZCYCCGHJ/settings/pull-requests HTTP/1.1
09:53:03.826 [Test worker] DEBUG jclouds.wire - >> "{"mergeConfig":{"defaultStrategy":{"id":"squash"},"strategies":[{"id":"squash"}],"type":"REPOSITORY"},"requiredAllApprovers":false,"requiredAllTasksComplete":false,"requiredApprovers":0,"requiredSuccessfulBuilds":1}"
09:53:03.826 [Test worker] DEBUG jclouds.headers - >> POST http://127.0.0.1:7990/rest/api/1.0/projects/DEV/repos/YUZCYCCGHJ/settings/pull-requests HTTP/1.1
09:53:03.826 [Test worker] DEBUG jclouds.headers - >> Accept: application/json
09:53:03.826 [Test worker] DEBUG jclouds.headers - >> Authorization: Basic bWFydGluOm1hcnRpbg==
09:53:03.826 [Test worker] DEBUG jclouds.headers - >> Content-Type: application/json
09:53:03.826 [Test worker] DEBUG jclouds.headers - >> Content-Length: 215
09:53:03.978 [Test worker] DEBUG org.jclouds.http.internal.JavaUrlHttpCommandExecutorService - Receiving response 1402237253: HTTP/1.1 200 null
09:53:03.978 [Test worker] DEBUG jclouds.headers - << HTTP/1.1 200 null
09:53:03.978 [Test worker] DEBUG jclouds.headers - << Transfer-Encoding: chunked
09:53:03.978 [Test worker] DEBUG jclouds.headers - << X-AREQUESTID: @1YRPAXLx593x165x0
09:53:03.978 [Test worker] DEBUG jclouds.headers - << X-ASEN: SEN-11797004
09:53:03.978 [Test worker] DEBUG jclouds.headers - << X-Content-Type-Options: nosniff
09:53:03.978 [Test worker] DEBUG jclouds.headers - << X-AUSERNAME: martin
09:53:03.979 [Test worker] DEBUG jclouds.headers - << Vary: X-AUSERNAME,Accept-Encoding
09:53:03.979 [Test worker] DEBUG jclouds.headers - << X-AUSERID: 1
09:53:03.979 [Test worker] DEBUG jclouds.headers - << Date: Wed, 08 Aug 2018 13:53:03 GMT
09:53:03.979 [Test worker] DEBUG jclouds.headers - << Cache-Control: no-cache, no-transform
09:53:03.979 [Test worker] DEBUG jclouds.headers - << Content-Type: application/json;charset=UTF-8
09:53:03.979 [Test worker] DEBUG jclouds.wire - << "{"mergeConfig":{"defaultStrategy":{"description":"Combine all commits into one new non-merge commit on the target branch.","enabled":true,"flag":"--squash","id":"squash","name":"Squash"},"strategies":[{"description":"Always create a new merge commit and update the target branch to it, even if the source branch is already up to date with the target branch.","enabled":false,"flag":"--no-ff","id":"no-ff","name":"Merge commit"},{"description":"If the source branch is out of date with the target branch, create a merge commit. Otherwise, update the target branch to the latest commit on the source branch.","enabled":false,"flag":"--ff","id":"ff","name":"Fast-forward"},{"description":"If the source branch is out of date with the target branch, reject the merge request. Otherwise, update the target branch to the latest commit on the source branch.","enabled":false,"flag":"--ff-only","id":"ff-only","name":"Fast-forward only"},{"description":"Rebase commits from the source branch onto the target branch, creating a new non-merge commit for each incoming commit, and create a merge commit to update the target branch.","enabled":false,"flag":"rebase + merge --no-ff","id":"rebase-no-ff","name":"Rebase and merge"},{"description":"Rebase commits from the source branch onto the target branch, creating a new non-merge commit for each incoming commit, and fast-forward the target branch with the resulting commits.","enabled":false,"flag":"rebase + merge --ff-only","id":"rebase-ff-only","name":"Rebase and fast-forward"},{"description":"Combine all commits into one new non-merge commit on the target branch.","enabled":true,"flag":"--squash","id":"squash","name":"Squash"},{"description":"If the source branch is out of date with the target branch, reject the merge request. Otherwise, combine all commits into one new non-merge commit on the target branch.","enabled":false,"flag":"--squash --ff-only","id":"squash-ff-only","name":"Squash, fast-forward only"}],"type":"REPOSITORY"},"requiredAllApprovers":false,"requiredAllTasksComplete":false,"requiredApprovers":0,"requiredSuccessfulBuilds":1,"com.atlassian.bitbucket.server.bitbucket-bundled-hooks:requiredApprovers":{"enable":false,"count":0},"com.atlassian.bitbucket.server.bitbucket-build:requiredBuilds":{"enable":false,"count":0}}"
09:53:03.988 [Test worker] ERROR org.jclouds.http.functions.ParseJson - Error parsing input: No enum constant com.cdancy.bitbucket.rest.domain.repository.MergeStrategy.MergeStrategyId.rebase-no-ff
java.lang.IllegalArgumentException: No enum constant com.cdancy.bitbucket.rest.domain.repository.MergeStrategy.MergeStrategyId.rebase-no-ff
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.jclouds.json.internal.EnumTypeAdapterThatReturnsFromValue.deserialize(EnumTypeAdapterThatReturnsFromValue.java:41)
	at org.jclouds.json.internal.EnumTypeAdapterThatReturnsFromValue.deserialize(EnumTypeAdapterThatReturnsFromValue.java:32)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
	at org.jclouds.json.internal.DeserializationConstructorAndReflectiveTypeAdapterFactory$ParameterReader.read(DeserializationConstructorAndReflectiveTypeAdapterFactory.java:273)
	at org.jclouds.json.internal.DeserializationConstructorAndReflectiveTypeAdapterFactory$DeserializeIntoParameterizedConstructor.read(DeserializationConstructorAndReflectiveTypeAdapterFactory.java:185)
	at org.jclouds.json.internal.NullFilteringTypeAdapterFactories$IterableTypeAdapter.readAndBuild(NullFilteringTypeAdapterFactories.java:95)
	at org.jclouds.json.internal.NullFilteringTypeAdapterFactories$IterableTypeAdapter.read(NullFilteringTypeAdapterFactories.java:83)
	at org.jclouds.json.internal.NullFilteringTypeAdapterFactories$IterableTypeAdapter.read(NullFilteringTypeAdapterFactories.java:62)
	at org.jclouds.json.internal.DeserializationConstructorAndReflectiveTypeAdapterFactory$ParameterReader.read(DeserializationConstructorAndReflectiveTypeAdapterFactory.java:273)
	at org.jclouds.json.internal.DeserializationConstructorAndReflectiveTypeAdapterFactory$DeserializeIntoParameterizedConstructor.read(DeserializationConstructorAndReflectiveTypeAdapterFactory.java:185)
	at org.jclouds.json.internal.DeserializationConstructorAndReflectiveTypeAdapterFactory$ParameterReader.read(DeserializationConstructorAndReflectiveTypeAdapterFactory.java:273)
	at org.jclouds.json.internal.DeserializationConstructorAndReflectiveTypeAdapterFactory$DeserializeIntoParameterizedConstructor.read(DeserializationConstructorAndReflectiveTypeAdapterFactory.java:185)
	at com.google.gson.Gson.fromJson(Gson.java:861)
	at com.google.gson.Gson.fromJson(Gson.java:826)
	at org.jclouds.json.internal.GsonWrapper.fromJson(GsonWrapper.java:55)
	at org.jclouds.http.functions.ParseJson.apply(ParseJson.java:82)
	at org.jclouds.http.functions.ParseJson.apply(ParseJson.java:76)
	at org.jclouds.http.functions.ParseJson.apply(ParseJson.java:61)
	at org.jclouds.http.functions.ParseJson.apply(ParseJson.java:41)
	at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:91)
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:74)
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:45)
	at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy61.updatePullRequestSettings(Unknown Source)
	at com.cdancy.bitbucket.rest.features.RepositoryApiLiveTest.testUpdatePullRequestSettings(RepositoryApiLiveTest.java:121)
...
```

**Comment by cdancy** [comment] 2018-08-08 15:14
We just recently upgraded to 5.9.1 and I've yet to try against that version but Bitbucket is pretty good about backwards compatibility which is why I never check things. I can't remember what we were on before the upgrade but it was definitely 5.x. Let me give things a go now and see what I get. Stay tuned...

**Comment by martinda** [comment] 2018-08-08 15:45
I am noticing something strange in the stdout, the git commands appear to be empty.

```
...
git-tag-commit: 
git-push: 
git-branch: 
git-branch-add: 
git-branch-commit: [9fcf6921e3564442ae0e096f3e733809 f137fb1] added
 1 file changed, 1 insertion(+)
 create mode 100644 79a52b1f054043919464434483e594ea.txt
git-branch-push:
...
```
This is odd since `TestUtilities.java` does print something to the terminal after printing the intent:
https://github.com/cdancy/bitbucket-rest/blob/master/src/test/java/com/cdancy/bitbucket/rest/TestUtilities.java#L236-L262

**Comment by martinda** [comment] 2018-08-08 15:56
I found the problem I think... I added some println statements and discovered this:
```
[git, push, --tags, -u, http://martin@127.0.0.1:7990/scm/dev/gwhkngrsqb.git, 95806e780dee47d7bc29f53f2fb986cb]
/home/martin/git/bitbucket-rest/build/integ-projects/f294487e7c7443c5985b4e7db454a257
git-branch-push: 
```
Then I ran the command from the terminal:
```
cd /home/martin/git/bitbucket-rest/build/integ-projects/f294487e7c7443c5985b4e7db454a257
cosmo:f294487e7c7443c5985b4e7db454a257 (95806e780dee47d7bc29f53f2fb986cb) git push --tags -u http://martin@127.0.0.1:7990/scm/dev/gwhkngrsqb.git 95806e780dee47d7bc29f53f2fb986cb
Password for 'http://martin@127.0.0.1:7990':
```
It stops and asks for the password.

**Comment by martinda** [comment] 2018-08-08 16:31
Most of the tests now pass but I needed to add my credentials to my `~/.netrc` file... Now only three tests fail.

**Comment by cdancy** [comment] 2018-08-08 16:38
@martinda so running the branches live test worked for me ... however when looking at the documentation I do see that when a repository is empty Bitbucket will return a 204 with no content which is a case which is not currently supported. I can make a fix for that now.

https://docs.atlassian.com/bitbucket-server/rest/5.13.0/bitbucket-rest.html?utm_source=%2Fstatic%2Frest%2Fbitbucket-server%2Flatest%2Fbitbucket-rest.html&utm_medium=301#idm46209338076752

The other issue you noted is due to lack of supported merge strategies which I can also address. Would you mind testing a branch with the changes once I send them in?

**Comment by martinda** [comment] 2018-08-08 17:09
@cdancy yes, I have a bit of time in the next couple of days, I can help run some tests.

This is one of the three remaining errors I get:
```
java.lang.AssertionError: 
Expecting empty but was:<[Error{context=null, message=TestUserName2 does not have permission to view this pull request., exceptionName=com.atlassian.bitbucket.pull.InvalidPullRequestParticipantException, conflicted=false, vetoes=[]}]>
	at com.cdancy.bitbucket.rest.features.PullRequestApiLiveTest.testAssignParticipants(PullRequestApiLiveTest.java:217)
```
The stdout shows:
```
12:33:12.158 [Test worker] DEBUG jclouds.headers - >> POST http://127.0.0.1:7990/rest/api/1.0/projects/DEV/repos/DTFNEXCPRI/pull-requests/1/participants HTTP/1.1
12:33:12.159 [Test worker] DEBUG jclouds.headers - >> Accept: application/json
12:33:12.159 [Test worker] DEBUG jclouds.headers - >> Authorization: Basic bWFydGluOm1hcnRpbg==
12:33:12.159 [Test worker] DEBUG jclouds.headers - >> Content-Type: application/json
12:33:12.159 [Test worker] DEBUG jclouds.headers - >> Content-Length: 365
12:33:12.172 [Test worker] DEBUG org.jclouds.http.internal.JavaUrlHttpCommandExecutorService - Receiving response -101380746: HTTP/1.1 409 null
12:33:12.172 [Test worker] DEBUG jclouds.headers - << HTTP/1.1 409 null
12:33:12.172 [Test worker] DEBUG jclouds.headers - << Transfer-Encoding: chunked
12:33:12.172 [Test worker] DEBUG jclouds.headers - << X-AREQUESTID: @1YRPAXLx753x2123x0
12:33:12.172 [Test worker] DEBUG jclouds.headers - << X-ASEN: SEN-11797004
12:33:12.172 [Test worker] DEBUG jclouds.headers - << X-Content-Type-Options: nosniff
12:33:12.172 [Test worker] DEBUG jclouds.headers - << X-AUSERNAME: martin
12:33:12.172 [Test worker] DEBUG jclouds.headers - << Vary: X-AUSERNAME,Accept-Encoding
12:33:12.172 [Test worker] DEBUG jclouds.headers - << X-AUSERID: 1
12:33:12.172 [Test worker] DEBUG jclouds.headers - << Date: Wed, 08 Aug 2018 16:33:11 GMT
12:33:12.172 [Test worker] DEBUG jclouds.headers - << Cache-Control: no-cache, no-transform
12:33:12.172 [Test worker] DEBUG jclouds.headers - << Content-Type: application/json;charset=UTF-8
12:33:12.173 [Test worker] DEBUG jclouds.wire - << "{"errors":[{"context":null,"message":"TestUserName2 does not have permission to view this pull request.","exceptionName":"com.atlassian.bitbucket.pull.InvalidPullRequestParticipantException"}]}"
```

**Comment by martinda** [comment] 2018-08-09 13:43
@cdancy I looked into the `TestUserName2` problem and it looks like the test user does not have the necessary read permission into the project where the pull-request is created. There is a REST API to add a user to a project or to a repository, but it has not been implemented. I propose to create a PR that adds API methods to resolve this issue.

**Comment by cdancy** [comment] 2018-08-09 13:47
@martinda yeah that would be ideal. That, potentially combined with `AdminApi.createUser` if we test user has the right privileges, would be the proper way to do things.

**Comment by cdancy** [comment] 2018-08-22 01:08
Changes for this have been merged to master.

**Closed by cdancy** 2018-08-22 01:08 UTC
Labels: bug, question
